Added support for tips for non_staff users
trojsten/django-tips pull request #3
Opened 2017-01-24 14:42 UTC by mhozza

2017-01-24 18:12 UTC, maaario commented on tips/models.py
> +    sites = models.ManyToManyField(Site, blank=True)
Možno proidať help text, že keď sa nezadá žiadna site, zobrazuje sa to na všetkých?

2017-01-24 18:26 UTC, maaario requested changes
Mohol by si ešte doplniť stĺpčeky do admin-list-view: for staff / for non_staff (možno aj sites, ale keďže to M-M tak sa aj tak nebude dať podľa toho usporiadavať ... sites filter?)

Druhá vec je, že tuším, keď sa zobrazí tip, tak je tam nejaký text, že tip po zaškrtnutí nikdy neuvidíš, ale môžeš si ho pozrieť v adminovi ... je to tam, alebo sa mi to len zdá? Ak áno, treba to zobrazovať len staffom.

2017-01-25 18:56 UTC, mhozza commented
Migracie su spravene tak ze vsetky stare tipy budu staff only (vratane toho o admin rozhrani).

stlpce doplnim + mozem spravit aj dake filtre na sites a pod.

2017-01-25 19:35 UTC, maaario commented
Aha, jasne, to o admin rozhrani bol len jeden tip. 
Myslel som si, ze sa to zobrazovalo na kazdom tipe, tak potom ok.

2017-01-25 20:56 UTC, maaario approved these changes

2017-01-25 21:32 UTC, merged