Make self-sufficient static files
trojsten/django-tips pull request #6
Opened 2018-01-22 12:35 UTC by kubik369

2018-01-25 21:18 UTC, mhozza requested changes

2018-01-25 21:18 UTC, mhozza commented on tips/views.py
> +    if user.is_anonymous:
Pls. pridaj velmi jednoduchy test k tymto 2 metodam.

2018-01-25 21:18 UTC, mhozza commented on example/static/js/csrf_token.js
> -/**
Django teraz place ze nema example/static adresar. Bud vyrob prazdny adresar so suborom .gitkeep, alebo skus zistit ako spravit settings tak aby to nepotreboval.

Problem sa objavi az ked sa pokusis naladovat stranku.

2018-02-07 19:22 UTC, mhozza commented on tips/views.py
> +    if user.is_anonymous:
nieco stylu zavolaj tuto metodu bud priamo alebo cez http api a zisti ci vratila daky tip.
Ak sa ti velmi nechce tak pass, len mi prislo zaujimave ze to funguje aj so zatvorkami aj bez (ci?) ze ak nahodou nieco nefunguje tak test by to mohol odhalit.

2018-02-07 19:27 UTC, kubik369 commented on tips/views.py
> +    if user.is_anonymous:
Nefungovalo to so zátvorkami, preto som to zmenil. Snažím sa to otestovať, ale nechce to spolupracovať

2018-02-07 20:45 UTC, mhozza approved these changes
Vdaka!

2018-04-23 19:52 UTC, merged